name = "autha-worker"
main = "src/index.js"
compatibility_date = "2024-12-01"

[vars]
AUTHA_CAPTCHA_TTL_SECONDS = "120"

[[kv_namespaces]]
binding = "AUTHA_KV"
id = "f852295d4aac43a29b7a43ebbf29ca90"

[[migrations]]
tag = "v2"
deleted_classes = ["AuthaRecordStore"]

